const customPoolPart3 = [
  {
    q: "What does 'Management by Objectives' transition into in modern, adaptable enterprises?",
    opts: [{t:"Management by continuous learning and improvement", c:true}, {t:"Total Quality Management (TQM)", c:false}, {t:"Management by strict quotas", c:false}, {t:"Management by exceptions", c:false}],
    exp: "<b>Concept: Enterprise Management</b><br>Setting rigid goals (objectives) for a year is outdated because the market changes too fast. The modern approach is Agile-style continuous learning, where the company constantly adapts its goals and learns from its iterative failures."
  },
  {
    q: "Which group of professionals is intentionally brought into the conceptual design phase in Concurrent Engineering?",
    opts: [{t:"Only Software Developers", c:false}, {t:"Manufacturing engineers and Marketing specialists", c:true}, {t:"Only Mechanical Engineers", c:false}, {t:"Government regulators", c:false}],
    exp: "<b>Concept: Concurrent Engineering</b><br>Concurrent Engineering breaks down silos. By bringing Manufacturing (who know how to build it) and Marketing (who know what the customer wants) into the room on Day 1, the Designer avoids making a product that is impossible to build or impossible to sell."
  },
  {
    q: "A line is drawn from (0,0,0) to (10,10,10) in CAD. This is an example of:",
    opts: [{t:"A Synthetic curve", c:false}, {t:"An Analytical curve", c:true}, {t:"A B-spline", c:false}, {t:"A surface of revolution", c:false}],
    exp: "<b>Concept: Curve Types</b><br>A straight line is the most basic analytical curve. It is defined by a perfect, simple mathematical equation, unlike synthetic curves which rely on complex algorithms to trace between control points."
  },
  {
    q: "Why is 'Feature Recognition' critical for Computer-Aided Process Planning (CAPP)?",
    opts: [{t:"Because CAPP needs to know what colors to paint the part", c:false}, {t:"Because raw CAD geometry is just dumb faces and edges; CAPP must 'recognize' these as holes or slots to assign the correct machining tools", c:true}, {t:"Because it calculates the financial cost of the part", c:false}, {t:"Because it guides the AGVS robots", c:false}],
    exp: "<b>Concept: CAPP (Computer-Aided Process Planning)</b><br>A CAD file doesn't say 'I am a hole'. It just says 'Here is a cylinder subtracted from a box'. Feature Recognition algorithms scan that math and logically deduce what the feature is, which is the first step in deciding how to manufacture it."
  },
  {
    q: "What defines 'Discrete Event Systems' in production automation?",
    opts: [{t:"Chemicals mixing in a continuous flow", c:false}, {t:"Manufacturing items (like cars or phones) in distinct, countable steps or events", c:true}, {t:"Generating electricity constantly", c:false}, {t:"Software crashing randomly", c:false}],
    exp: "<b>Concept: Production Automation</b><br>Unlike continuous systems (oil refineries, water treatment), discrete systems build physical, countable parts. An 'event' triggers the next step (e.g., Part arrives -> Sensor triggers -> Robot drills hole)."
  },
  {
    q: "What is the primary characteristic of a 'Ruled Surface' in 3D modeling?",
    opts: [{t:"It is generated by sweeping a straight line across two different boundary curves", c:true}, {t:"It is generated by revolving a circle", c:false}, {t:"It is a perfect solid sphere", c:false}, {t:"It is defined by Boolean subtraction", c:false}],
    exp: "<b>Concept: 3D Surface Generation</b><br>A ruled surface is created when you take a straight line (the rule) and slide it along two distinct rails or curves. For example, a cylinder is a ruled surface (sliding a straight line around two circular rails)."
  },
  {
    q: "In GKS, what state must the system be in to actively record a new geometric shape?",
    opts: [{t:"Workstation Open", c:false}, {t:"GKS Closed", c:false}, {t:"Segment Open", c:true}, {t:"Segment Closed", c:false}],
    exp: "<b>Concept: GKS State Machine</b><br>A segment is a container for graphics. To put graphics inside the container, you must transition the system into the 'Segment Open' state. Once open, any primitives you draw are recorded into that segment."
  },
  {
    q: "Why can't you apply a geometric transformation (like rotation) to an OPEN segment in GKS?",
    opts: [{t:"Because rotation is physically impossible in 2D", c:false}, {t:"Because the segment is currently recording new primitives and hasn't defined its final boundaries yet", c:true}, {t:"Because the workstation is turned off", c:false}, {t:"Because open segments are instantly deleted", c:false}],
    exp: "<b>Concept: GKS Segment Rules</b><br>Transformations in GKS are applied to the segment as a whole entity. While a segment is open, it is incomplete. The math cannot apply a rotation matrix to an undefined, growing entity. It must be closed first."
  },
  {
    q: "What is the function of the WISS (Workstation Independent Segment Storage) in GKS?",
    opts: [{t:"It stores segments permanently on the hard drive", c:false}, {t:"It temporarily stores segments in a generic, device-independent format so they can be sent to multiple different workstations later", c:true}, {t:"It draws the CAD geometry", c:false}, {t:"It physically manufactures the part", c:false}],
    exp: "<b>Concept: GKS Architecture</b><br>WISS acts as a central memory bank. Instead of sending a drawing directly to a printer and losing it, you save it in WISS. From WISS, you can blast that exact same drawing to a 1080p screen, a 4k screen, and a plotter simultaneously."
  },
  {
    q: "Which factor is an 'Internal' influence on an enterprise's adaptability?",
    opts: [{t:"Government Public Policy", c:false}, {t:"Market Demand", c:false}, {t:"The Technology systems the enterprise chooses to implement", c:true}, {t:"Client requests", c:false}],
    exp: "<b>Concept: Enterprise Management</b><br>A company adapts using the tools it controls. The management hierarchy and the technology software stack it buys are internal choices. If they buy rigid, outdated technology, their internal adaptability drops."
  },
  {
    q: "What does 'SCD' stand for in the GKS transformation pipeline?",
    opts: [{t:"System Coordinates Device", c:true}, {t:"System Coordinates Descriptive", c:false}, {t:"Screen Color Display", c:false}, {t:"Segment Control Data", c:false}],
    exp: "<b>Concept: GKS Pipeline</b><br>SCD represents the final step in the graphics pipeline. It stands for System Coordinates Device, which is the specific grid of physical pixels (or ink dots) for the exact hardware monitor or printer being used."
  },
  {
    q: "What is the purpose of 'Dimension Lines' in technical drafting?",
    opts: [{t:"To physically cut the part", c:false}, {t:"To visually indicate the direction and extent of a measurement across the part", c:true}, {t:"To write paragraphs of text", c:false}, {t:"To mark the center of a circle", c:false}],
    exp: "<b>Concept: Technical Drafting</b><br>A dimension line is the thin line (usually with arrows on the ends) that spans the gap between two extension lines. It acts as the visual 'ruler' showing exactly what distance the numerical text is describing."
  },
  {
    q: "In the context of CIM, what does the AGVS handle?",
    opts: [{t:"Automated Guided Vehicle System - handles internal factory floor transport between machines", c:true}, {t:"Automated Geometric Visualization System - renders 3D graphics", c:false}, {t:"Automated G-code Validation System - checks code for errors", c:false}, {t:"Automated Storage System - warehouses raw materials", c:false}],
    exp: "<b>Concept: Factory Hardware</b><br>AGVS consists of the mobile robots driving around the factory. They are the 'veins' of the factory, moving raw materials from the ASRS warehouse to the FMS machining cells, and moving finished parts to shipping."
  },
  {
    q: "Why do engineers use 'Homogeneous Coordinates' (1x4 matrix) instead of 'Natural Coordinates' (1x3 matrix) in 3D graphics?",
    opts: [{t:"Because it looks more professional", c:false}, {t:"Because it unifies Translation, Rotation, and Scaling into a single multiplication process, drastically speeding up rendering", c:true}, {t:"Because CAD monitors require 4 dimensions", c:false}, {t:"Because it removes the Z-axis", c:false}],
    exp: "<b>Concept: Computer Graphics Math</b><br>Without the 4th dummy coordinate 'W', translating (moving) an object requires matrix addition, while rotating requires matrix multiplication. Homogeneous coordinates trick the math so EVERYTHING can be done via fast, chained multiplication."
  },
  {
    q: "What is the difference between an 'Abstract Feature' and a 'Concrete Feature'?",
    opts: [{t:"Abstract features exist in the physical world; Concrete features do not", c:false}, {t:"Abstract features represent functional intent without final exact geometry; Concrete features have every dimension perfectly defined", c:true}, {t:"Abstract features are only used for marketing; Concrete features are for engineering", c:false}, {t:"There is no difference", c:false}],
    exp: "<b>Concept: Conceptual Design</b><br>During brainstorming, you might place an 'abstract' cylinder and call it a 'shaft', knowing it will transfer power. You don't know its exact thickness yet. Once you do the stress math and lock its diameter to exactly 25mm, it becomes a concrete feature."
  },
  {
    q: "What is a 'Polymarker' used for in 2D drafting?",
    opts: [{t:"To draw a straight line between two points", c:false}, {t:"To fill an area with a solid color", c:false}, {t:"To place a specific, identifiable symbol (like a crosshair) at a single exact coordinate", c:true}, {t:"To extrude a 2D shape into 3D", c:false}],
    exp: "<b>Concept: GKS Primitives</b><br>If an engineer needs to clearly mark the exact center of rotation for a gear, they don't draw a tiny circle. They use a Polymarker primitive to drop a crosshair exactly at that node."
  },
  {
    q: "Which Boolean operation is used to hollow out a cube by pushing a cylinder through it?",
    opts: [{t:"Union", c:false}, {t:"Intersection", c:false}, {t:"Subtraction / Difference", c:true}, {t:"Sweeping", c:false}],
    exp: "<b>Concept: CSG Operations</b><br>Subtraction (or Difference) takes the volume of Object A and permanently cuts away any overlapping volume from Object B. Pushing a cylinder through a cube and subtracting it leaves a perfect cylindrical hole."
  },
  {
    q: "How does the 'Descriptive' model of design differ from the 'Prescriptive' model?",
    opts: [{t:"Descriptive observes the messy, rapid trial-and-error loops of real engineers; Prescriptive defines the ideal, strict logical steps engineers *should* take", c:true}, {t:"Descriptive is only for 2D; Prescriptive is for 3D", c:false}, {t:"Descriptive creates the G-code; Prescriptive creates the CAD file", c:false}, {t:"There is no difference", c:false}],
    exp: "<b>Concept: Design Methodology</b><br>The Prescriptive model is a clean textbook flowchart (Problem -> Concept -> Detail). The Descriptive model studies human psychology and realizes that humans actually rapidly guess (Generate Operations) and check (Evaluate) in messy loops."
  },
  {
    q: "What is the future concept for 'technology-oriented solutions'?",
    opts: [{t:"Highly custom, bespoke software written from scratch for every company", c:false}, {t:"Generic, highly adaptable packages and systems that can scale and configure to any business out-of-the-box", c:true}, {t:"Removing all technology from the factory", c:false}, {t:"Monolithic databases", c:false}],
    exp: "<b>Concept: Future IT Architecture</b><br>In the past, companies paid millions to write custom software from scratch. Today (and in the future), companies buy massive, generic ERP systems (like SAP) that are flexible enough to adapt to their specific business needs."
  },
  {
    q: "In the formula 'Collections of intelligent agents = intelligent systems', what does an 'intelligent agent' represent?",
    opts: [{t:"A human manager", c:false}, {t:"A small, independent, specialized piece of software (microservice) that collaborates with other agents to run the factory", c:true}, {t:"A dumb database", c:false}, {t:"A raw block of metal", c:false}],
    exp: "<b>Concept: Software Architecture</b><br>Instead of one giant program running the whole factory, modern architecture uses hundreds of tiny software 'agents'. One agent only handles conveyor belt speed. Another only handles temperature. By talking to each other, they create a massive, intelligent system."
  }
];
