const customPoolPart2 = [
  {
    q: "What is the primary function of a Flexible Manufacturing System (FMS)?",
    opts: [{t:"To provide a fully automated, adaptable workcell containing CNC machines and local robots that can quickly switch between producing different part types", c:true}, {t:"To generate the 2D CAD drafts", c:false}, {t:"To store massive amounts of raw material in a warehouse", c:false}, {t:"To calculate the company's financial taxes", c:false}],
    exp: "<b>Concept: FMS (Flexible Manufacturing System)</b><br>An FMS is the physical 'heart' of the modern factory. It is a cluster of automated machines (like CNC mills and lathes) interconnected by local robots. Its key feature is 'flexibility'—it can switch from making Engine A to Engine B almost instantly, without human retooling."
  },
  {
    q: "In the context of CIM, what is the role of CAE (Computer-Aided Engineering)?",
    opts: [{t:"To draw the initial 2D sketches", c:false}, {t:"To physically cut the metal", c:false}, {t:"To simulate and test the physical properties of the CAD model (e.g., stress, thermal dynamics, fluid flow) before manufacturing", c:true}, {t:"To manage employee payroll", c:false}],
    exp: "<b>Concept: CAE (Computer-Aided Engineering)</b><br>CAE software takes the pure geometry from CAD and applies physics to it. Engineers use CAE (often using Finite Element Analysis) to see if a part will break under pressure or melt under heat, saving massive amounts of money on physical prototypes."
  },
  {
    q: "Why is 'Design Knowledge' crucial in the scientific approach to design?",
    opts: [{t:"Because it allows designers to ignore physical laws", c:false}, {t:"Because it provides the formalized rules, past experiences, and technical data necessary to create safe and functional products", c:true}, {t:"Because it focuses purely on artistic intuition", c:false}, {t:"Because it slows down the CAD software", c:false}],
    exp: "<b>Concept: Design Science</b><br>Engineering isn't just drawing; it relies on established physics, material science, and past successes/failures. Design Knowledge (stored in databases, standards, and expert systems) ensures every new design stands on the shoulders of proven engineering."
  },
  {
    q: "In CAD, a 'Spline' is heavily utilized because:",
    opts: [{t:"It represents a perfect circle", c:false}, {t:"It only draws straight lines", c:false}, {t:"It allows the creation of smooth, complex, and continuous organic curves that pass near or through control points", c:true}, {t:"It calculates the volume of the part", c:false}],
    exp: "<b>Concept: Synthetic Curves</b><br>In industries like aerospace or automotive, surfaces must be aerodynamically smooth and organic (not just simple circles and boxes). Splines (like B-splines or NURBS) provide the mathematical framework to build these complex, flowing shapes."
  },
  {
    q: "What defines a 'surface of revolution'?",
    opts: [{t:"Extruding a shape in a straight line", c:false}, {t:"Spinning a 2D generator shape around a central linear axis for a specific angle", c:true}, {t:"Combining two solid boxes", c:false}, {t:"Trimming a circle in half", c:false}],
    exp: "<b>Concept: 3D Generation</b><br>If you want to model a tire, a vase, or a shaft, you draw the 2D cross-section (the generator) and revolve it 360 degrees around a central axis. This sweeping motion creates a surface of revolution."
  },
  {
    q: "Which GKS primitive is used to clearly mark a specific coordinate point on a drawing (e.g., a center point)?",
    opts: [{t:"Polyline", c:false}, {t:"Text", c:false}, {t:"Fill Area", c:false}, {t:"Polymarker", c:true}],
    exp: "<b>Concept: GKS Primitives</b><br>While a Polyline draws paths and boundaries, a Polymarker is explicitly used to drop a specific symbol (like a cross or an asterisk) at a single coordinate to mark an important node or center of rotation."
  },
  {
    q: "In an Expert System, what is the fundamental difference between the Knowledge Base and the Inference Engine?",
    opts: [{t:"The Knowledge Base holds data/facts; the Inference Engine holds the logical rules (code) to process that data", c:true}, {t:"The Knowledge Base holds rules; the Inference Engine holds facts", c:false}, {t:"They are the exact same thing", c:false}, {t:"The Knowledge Base draws the CAD model", c:false}],
    exp: "<b>Concept: Expert Systems Architecture</b><br>Expert systems separate data from logic. If a new material is invented, you just add the fact to the Knowledge Base without rewriting the code in the Inference Engine. The engine uses its IF-THEN rules to query the newly updated database."
  },
  {
    q: "In 2D drafting, what defines an 'analytical curve'?",
    opts: [{t:"A curve that cannot be described mathematically", c:false}, {t:"A curve algorithmically generated by control points", c:false}, {t:"A curve that is perfectly defined by a simple, exact mathematical equation (like y = mx + b)", c:true}, {t:"A 3D solid", c:false}],
    exp: "<b>Concept: Analytical Geometry</b><br>Analytical curves include straight lines, perfect circles, and conic sections (parabolas, ellipses). They are fundamental because their exact coordinate at any point can be found by plugging numbers into a single equation."
  },
  {
    q: "What is the primary role of a 'Workstation' in the GKS standard?",
    opts: [{t:"To physically machine the part", c:false}, {t:"To act as the logical interface to a physical graphical device (like a monitor or plotter), managing its specific capabilities", c:true}, {t:"To store the Knowledge Base", c:false}, {t:"To generate G-code", c:false}],
    exp: "<b>Concept: GKS Architecture</b><br>In GKS, a 'workstation' isn't just the computer you sit at. It is an abstraction of a graphical output device (a screen, a printer). The GKS workstation handles the final translation of normalized graphics into the specific pixels or ink drops that device needs."
  },
  {
    q: "What is the key benefit of Concurrent Engineering involving marketing specialists early in the process?",
    opts: [{t:"They can physically weld the parts faster", c:false}, {t:"They write the CAD software", c:false}, {t:"They ensure the product being designed actually meets client needs and market demands, preventing expensive redesigns after manufacturing", c:true}, {t:"They operate the CNC machines", c:false}],
    exp: "<b>Concept: Concurrent Engineering</b><br>If engineers design a product in a vacuum, it might be perfectly manufactured but totally unsellable. Marketing teams provide critical external feedback (Client demands, Market trends) during the conceptual phase to keep the design profitable."
  },
  {
    q: "When a designer uses a 'Boolean Intersection' between a sphere and a cube, what is the result?",
    opts: [{t:"A shape containing the entire volume of both the sphere and the cube", c:false}, {t:"A shape containing only the volume where the sphere and cube physically overlap", c:true}, {t:"The sphere is hollowed out by the cube", c:false}, {t:"Two separate 2D circles", c:false}],
    exp: "<b>Concept: CSG Operations</b><br>Intersection (A ∩ B) deletes all material that belongs exclusively to object A and exclusively to object B. It only keeps the exact 3D space that is shared by BOTH objects simultaneously."
  },
  {
    q: "What differentiates a 'Design Feature' from a 'Manufacturing Feature'?",
    opts: [{t:"Design features fulfill engineering/functional requirements (e.g., strength); Manufacturing features are dictated by how the machine physically cuts the part", c:true}, {t:"Design features are 3D; Manufacturing features are 2D", c:false}, {t:"There is no difference", c:false}, {t:"Manufacturing features are only aesthetic", c:false}],
    exp: "<b>Concept: Feature Classification</b><br>A designer adds a 'rib' to stop a part from snapping under pressure (Design Feature). The machinist cuts a 'slot' because that's the shape the rotating drill bit makes when it moves (Manufacturing Feature)."
  },
  {
    q: "In a fully automated CIM factory, how do raw materials (semifabricates) move from the warehouse to the machines?",
    opts: [{t:"A human forklift driver brings them", c:false}, {t:"The ASRS crane retrieves them from the shelf and hands them to an AGVS robot, which drives them to the FMS", c:true}, {t:"The CAD software emails them", c:false}, {t:"They are 3D printed inside the machine", c:false}],
    exp: "<b>Concept: Factory Logistics</b><br>Total integration means machines talk to machines. The warehouse (ASRS) automatically retrieves the metal block. The automated guided vehicle (AGVS) picks it up and navigates the floor, delivering it directly to the flexible machining cell (FMS)."
  },
  {
    q: "Why is the 'Definition Space (DS)' fixed in relation to the model?",
    opts: [{t:"Because it is the absolute world coordinate system serving as the permanent anchor for all geometry", c:true}, {t:"Because the model is 2D", c:false}, {t:"Because the designer deletes it", c:false}, {t:"Because it maps directly to screen pixels", c:false}],
    exp: "<b>Concept: Coordinate Spaces</b><br>Every CAD file needs an absolute center of the universe (0,0,0) that never moves. This is the Definition Space. Even if the designer creates a temporary 'Model Space' to draw on a tilted angle, the software always mathematically ties those temporary coordinates back to the fixed DS."
  },
  {
    q: "How does CAPP (Computer-Aided Process Planning) benefit the manufacturing pipeline?",
    opts: [{t:"It generates aesthetic marketing images", c:false}, {t:"It fully automates or assists in writing the complex 'recipe' (tools, speeds, paths) needed to build the part, reducing human error", c:true}, {t:"It manages the HR department", c:false}, {t:"It replaces the need for a CAD model", c:false}],
    exp: "<b>Concept: Process Planning</b><br>Before CAPP, a master machinist had to look at a blueprint and spend hours writing down exactly how to cut the metal safely. CAPP analyzes the CAD data and uses algorithms to generate standardized, safe, and highly efficient manufacturing plans automatically."
  },
  {
    q: "What defines 'Industry 4.0'?",
    opts: [{t:"The invention of the steam engine", c:false}, {t:"Mass production using electricity", c:false}, {t:"The integration of Cyber-Physical Systems (CPS), IoT, and cloud computing into manufacturing networks", c:true}, {t:"The use of basic computers in the 1970s", c:false}],
    exp: "<b>Concept: The Fourth Industrial Revolution</b><br>Industry 4.0 is about data. It takes the automated machines from the 3rd revolution and connects them to the internet (IoT). Now, a machine in Germany can analyze its own sensor data, realize it's breaking down, and automatically order a replacement part from a factory in China."
  },
  {
    q: "Which of the following is a key attribute of a 'Manufacturing Feature'?",
    opts: [{t:"Input/Output limitations of the tool (e.g., a drill bit's maximum depth)", c:true}, {t:"The color of the final product", c:false}, {t:"The marketing price", c:false}, {t:"The aesthetic font used on the logo", c:false}],
    exp: "<b>Concept: Manufacturing Attributes</b><br>A hole is a manufacturing feature. Its defining attributes are geometric (diameter), tolerance (how precise the cut must be), and tool limits (a drill bit can only physically go so deep before the machine crashes). Price and color are irrelevant to the milling machine."
  },
  {
    q: "What does the phrase 'Collections of intelligent agents = intelligent systems' represent?",
    opts: [{t:"A centralized mainframe architecture", c:false}, {t:"A modern, distributed IT architecture where independent software objects/agents collaborate to solve complex problems", c:true}, {t:"A physical group of human managers", c:false}, {t:"An old database model", c:false}],
    exp: "<b>Concept: Future IT Architecture</b><br>Instead of one massive, fragile computer program trying to do everything (monolithic architecture), the modern approach is microservices. Many small, independent 'intelligent agents' (like a payment agent, an inventory agent, a shipping agent) talk to each other to run the whole system efficiently."
  },
  {
    q: "In the Descriptive model of design, why do 'Operation Generation' and 'Evaluation' happen in rapid loops?",
    opts: [{t:"Because the software crashes often", c:false}, {t:"Because real-world designers rely on trial-and-error, generating an idea, testing it, and immediately tweaking it based on the results", c:true}, {t:"Because managers demand it", c:false}, {t:"Because it is the only way to write G-code", c:false}],
    exp: "<b>Concept: Descriptive vs Prescriptive</b><br>The descriptive model accepts that humans aren't perfect algorithms. A designer generates an idea (Operation Generation), looks at it (Evaluation), realizes it looks bad, and immediately generates a new idea. This messy, iterative loop is how real design happens."
  },
  {
    q: "What is the primary visual difference between a Wireframe model and a Solid B-Rep model?",
    opts: [{t:"Wireframes only show edges causing optical illusions (ambiguity); B-Reps define opaque faces clearly separating inside from outside", c:true}, {t:"Wireframes are 3D; B-Reps are 2D", c:false}, {t:"Wireframes calculate mass; B-Reps do not", c:false}, {t:"There is no visual difference", c:false}],
    exp: "<b>Concept: 3D Visualization</b><br>A wireframe draws only the skeletal lines (edges). Without faces to block the lines behind them, your brain can't tell if a box is popping out at you or sinking away (the Necker Cube illusion). B-Rep creates a solid skin, completely eliminating this ambiguity."
  },
  {
    q: "Which element is considered an 'External Factor' affecting an enterprise?",
    opts: [{t:"The internal management structure", c:false}, {t:"The software technology bought by the IT department", c:false}, {t:"Changes in government public policy (laws/regulations)", c:true}, {t:"The quality control team", c:false}],
    exp: "<b>Concept: Enterprise Adaptability</b><br>A company must adapt to forces it cannot control. It cannot control what laws the government passes (Public Policy), what its competitors do (Market), or what its buyers want (Clients). These are all External factors."
  },
  {
    q: "What is the purpose of the 'Normalized Coordinate System (SCN)' in GKS?",
    opts: [{t:"To physically print the document", c:false}, {t:"To act as a universal, device-independent middle ground (usually 0 to 1) before scaling to specific hardware", c:true}, {t:"To define the absolute real-world geometry", c:false}, {t:"To store segments", c:false}],
    exp: "<b>Concept: GKS Transformation Pipeline</b><br>Instead of writing custom math to translate real-world meters directly into pixels for a 1080p screen, a 4k screen, and a printer, GKS uses a middleman. It scales the meters into a generic 'Normalized' square (0 to 1). Then, individual workstation drivers scale that generic square to their specific hardware."
  },
  {
    q: "When a GKS Segment is OPEN, what is the primary restriction?",
    opts: [{t:"You cannot add any more primitives to it", c:false}, {t:"It cannot be geometrically transformed or have its attributes modified because it is not yet complete", c:true}, {t:"It deletes all previous segments", c:false}, {t:"It causes the workstation to shut down", c:false}],
    exp: "<b>Concept: GKS Segmentation Theory</b><br>An open segment is essentially 'recording mode'. Because the system doesn't know the final size or boundary of the drawing yet, it locks out global modifications. You must stop recording (Close the segment) before you can apply a transformation matrix to rotate or scale the whole group."
  },
  {
    q: "In PCB design, what is the key difference between THT and SMD?",
    opts: [{t:"THT components are glued to the surface; SMD components use pins through drilled holes", c:false}, {t:"THT components have physical pins that pass through drilled holes in the board; SMD components are soldered flat onto surface pads", c:true}, {t:"THT is for software; SMD is for hardware", c:false}, {t:"SMD requires a P&ID diagram", c:false}],
    exp: "<b>Concept: Electronics Manufacturing</b><br>THT (Through-Hole Technology) provides massive mechanical strength because the pins lock through the board. SMD (Surface Mount Device) provides massive density because the microscopic chips sit flat on the surface, allowing components on both sides without drilling."
  },
  {
    q: "Why is a P&ID diagram critical in process engineering?",
    opts: [{t:"It shows the exact 3D coordinates of every pipe in the building", c:false}, {t:"It logically maps the functional process flow of fluids, valves, and sensors, ensuring engineers understand how the system operates", c:true}, {t:"It calculates the weight of the water", c:false}, {t:"It acts as a mechanical stress test", c:false}],
    exp: "<b>Concept: Industrial Schematics</b><br>A P&ID (Piping and Instrumentation Diagram) is the master 'subway map' of a chemical plant. It doesn't care about physical distance; it cares about logic. It shows that Fluid A must pass through Valve B before hitting Sensor C, which is critical for programming the safety automation."
  },
  {
    q: "In a fully integrated CIM system, what does 'Logical, centralized data management' achieve?",
    opts: [{t:"It requires users to manually email files to each other", c:false}, {t:"It ensures all departments (CAD, CAM, CAPP, Management) read and write to a single source of truth, preventing outdated data from being manufactured", c:true}, {t:"It deletes old CAD files", c:false}, {t:"It disconnects the factory from the internet", c:false}],
    exp: "<b>Concept: Systemic Integration</b><br>If a designer updates a part in a file-based system, the machinist might accidentally manufacture the old version of the file. A centralized database ensures that the moment the designer hits 'save', the machinist's screen instantly updates to the new dimensions."
  },
  {
    q: "What defines an 'Abstract Feature' with engineering significance?",
    opts: [{t:"It is fully dimensioned and ready to manufacture", c:false}, {t:"It is just a random line with no purpose", c:false}, {t:"It represents a functional requirement (e.g., 'we need a hole here') but the exact geometry is not yet known", c:true}, {t:"It is a feature that cannot physically exist", c:false}],
    exp: "<b>Concept: Feature Design</b><br>During brainstorming (conceptual design), engineers know what the part needs to *do* before they know exactly what it will *look* like. They might place an 'abstract' hole feature as a placeholder, knowing it has structural significance, and define its exact diameter later during detail design."
  },
  {
    q: "Why are Homogeneous Coordinates (1x4 matrices) used in computer graphics instead of Natural Coordinates (1x3)?",
    opts: [{t:"Because 3D space actually has 4 physical dimensions", c:false}, {t:"They allow complex operations like Translation and Perspective Projection to be calculated using simple matrix multiplication", c:true}, {t:"They make the files smaller", c:false}, {t:"They are required for 2D drafting", c:false}],
    exp: "<b>Concept: Transformation Math</b><br>In standard 1x3 matrix math, you can easily rotate and scale by multiplying, but you have to *add* a matrix to translate (move) an object. By adding a dummy 4th coordinate 'W', computer graphics engines can unify everything into simple multiplication, drastically speeding up rendering."
  },
  {
    q: "What is the result of applying a 'Sweep' operation to a 2D generator without a trajectory?",
    opts: [{t:"It creates a perfect solid", c:false}, {t:"It extrudes infinitely", c:false}, {t:"The operation fails or creates nothing, because sweeping requires both a 2D shape AND a path to follow", c:true}, {t:"It creates a surface of revolution", c:false}],
    exp: "<b>Concept: Sweeping Operations</b><br>To sweep, you need a cookie cutter (the 2D generator profile) and a path to drag it along (the trajectory). Without the path, the shape has nowhere to go, and no 3D volume can be generated."
  },
  {
    q: "How does a 'Cylindrical (Parallel)' projection differ from human vision?",
    opts: [{t:"It has extreme perspective distortion", c:false}, {t:"It uses a focal point very close to the object", c:false}, {t:"Its projection rays are perfectly parallel (infinite distance), so objects do not appear smaller as they get further away", c:true}, {t:"It only displays in black and white", c:false}],
    exp: "<b>Concept: Projections</b><br>Human eyes use Central (Conic) projection, where rays converge into our pupil, making far things look small. Engineering blueprints often use Parallel projections (isometric) because a 10cm pipe looks exactly 10cm on the paper, regardless of whether it's in the foreground or background."
  }
];
