const customPoolPart1 = [
  {
    q: "Which of the following are examples of synthetic curves?",
    opts: [
      {t:"Bezier curve", c:true}, 
      {t:"B-spline curve", c:true}, 
      {t:"Perfect circle", c:false}, 
      {t:"Parabola", c:false}
    ],
    exp: "<b>Concept: Curves</b><br>Bezier and B-splines are synthetic curves generated by control points. Circles and parabolas are analytical curves defined by simple equations."
  },
  {
    q: "Constructive Solid Geometry (CSG) utilizes which of the following Boolean operations?",
    opts: [
      {t:"Union", c:true}, 
      {t:"Subtraction", c:true}, 
      {t:"Intersection", c:true}, 
      {t:"Extrusion", c:false}
    ],
    exp: "<b>Concept: CSG</b><br>CSG exclusively uses the Boolean operations Union, Subtraction, and Intersection to combine primitive shapes. Extrusion is a sweeping operation."
  },
  {
    q: "A Boundary Representation (B-Rep) model explicitly defines:",
    opts: [
      {t:"Vertices", c:true}, 
      {t:"Edges", c:true}, 
      {t:"Faces", c:true}, 
      {t:"CSG Trees", c:false}
    ],
    exp: "<b>Concept: B-Rep</b><br>B-Rep models define solids by stitching together an outer topological boundary consisting of faces, edges, and vertices. CSG trees belong to CSG modeling."
  },
  {
    q: "Which of the following are advantages of Solid Modeling over Surface Modeling?",
    opts: [
      {t:"Accurate calculation of center of gravity", c:true}, 
      {t:"Calculation of total mass", c:true}, 
      {t:"Precise collision detection", c:true}, 
      {t:"Faster wireframe rendering", c:false}
    ],
    exp: "<b>Concept: Solid Modeling</b><br>Because solid models contain volumetric data, you can calculate mass properties and accurately detect physical interference. Wireframes render faster, but aren't an advantage of solids."
  },
  {
    q: "Industry 4.0 is characterized by the use of:",
    opts: [
      {t:"Cyber-Physical Systems (CPS)", c:true}, 
      {t:"Internet of Things (IoT)", c:true}, 
      {t:"Cloud Computing", c:true}, 
      {t:"Steam-powered mechanization", c:false}
    ],
    exp: "<b>Concept: Industry 4.0</b><br>Industry 4.0 revolves around digital integration (CPS, IoT, Cloud). Steam power was the First Industrial Revolution."
  },
  {
    q: "In the GKS standard, which states exist before a workstation can actively draw?",
    opts: [
      {t:"GKS Closed", c:true}, 
      {t:"GKS Open", c:true}, 
      {t:"Workstation Open", c:true}, 
      {t:"Segment Open", c:false}
    ],
    exp: "<b>Concept: GKS States</b><br>Before drawing (Segment Open), the system must transition through GKS Closed -> GKS Open -> Workstation Open -> Workstation Active."
  },
  {
    q: "A Local Coordinate System (Model Space) in CAD is used to:",
    opts: [
      {t:"Act as a temporary, movable reference frame", c:true}, 
      {t:"Simplify sketching on angled 3D faces", c:true}, 
      {t:"Replace the absolute World Coordinate System", c:false}, 
      {t:"Define the final printed page layout", c:false}
    ],
    exp: "<b>Concept: Coordinate Spaces</b><br>Local Coordinate Systems are temporary, movable frames that allow designers to easily draw on angled surfaces without doing complex math."
  },
  {
    q: "According to the prescriptive design methodology, the primary phases include:",
    opts: [
      {t:"Problem Definition", c:true}, 
      {t:"Conceptual Design", c:true}, 
      {t:"Detail Design", c:true}, 
      {t:"Manufacturing", c:false}
    ],
    exp: "<b>Concept: Prescriptive Design</b><br>The three core phases are Problem Definition, Conceptual Design, and Detail Design. Manufacturing occurs after the design phase."
  },
  {
    q: "Which entities can be combined to form a continuous 2D Polyline?",
    opts: [
      {t:"Straight line segments", c:true}, 
      {t:"Arc segments", c:true}, 
      {t:"Spline segments", c:false}, 
      {t:"Solid primitives", c:false}
    ],
    exp: "<b>Concept: 2D Drafting</b><br>A standard polyline is a single, continuous entity composed entirely of connected straight line segments and arc segments."
  },
  {
    q: "What are the primary functions of using 'Layers' in a CAD drawing?",
    opts: [
      {t:"Logically grouping similar components", c:true}, 
      {t:"Toggling the visibility of specific systems", c:true}, 
      {t:"Changing colors of grouped lines globally", c:true}, 
      {t:"Extruding 2D shapes into 3D", c:false}
    ],
    exp: "<b>Concept: File Organization</b><br>Layers organize complex drawings by allowing engineers to group items (like electrical vs plumbing), toggle visibility, and apply global color/line styles."
  },
  {
    q: "Which of the following are standard 2D drafting primitives?",
    opts: [
      {t:"Polylines", c:true}, 
      {t:"Polymarkers", c:true}, 
      {t:"Text", c:true}, 
      {t:"Fill areas", c:true}
    ],
    exp: "<b>Concept: 2D Primitives</b><br>Basic 2D drawings rely on lines (polylines), nodes (polymarkers), annotations (text), and hatchings (fill areas). All four are correct."
  },
  {
    q: "Which of the following correctly describes a Central (Conic) projection?",
    opts: [
      {t:"The focal point is at a finite distance", c:true}, 
      {t:"It creates perspective distortion", c:true}, 
      {t:"The projection rays are perfectly parallel", c:false}, 
      {t:"Objects further away appear smaller", c:true}
    ],
    exp: "<b>Concept: Projections</b><br>Central projections use a finite focal point, causing rays to diverge into a cone. This inherently creates perspective, making distant objects smaller."
  },
  {
    q: "To successfully transfer a CAD model to a CAM system, the interface must preserve:",
    opts: [
      {t:"Geometric topology", c:true}, 
      {t:"Semantic metadata", c:true}, 
      {t:"Manufacturing feature intent", c:true}, 
      {t:"Screen pixel resolution", c:false}
    ],
    exp: "<b>Concept: System Integration</b><br>CAD-CAM integration requires geometry, topology, and semantic meaning (like identifying a hole). Screen pixels are irrelevant."
  },
  {
    q: "In parametric CAD modeling, changing a dimensional constraint will trigger:",
    opts: [
      {t:"Automatic recalculation of dependent geometry", c:true}, 
      {t:"Re-evaluation of related constraints", c:true}, 
      {t:"Complete deletion of the model", c:false}, 
      {t:"Generation of a new file", c:false}
    ],
    exp: "<b>Concept: Parametric Modeling</b><br>Parametric models use mathematical relationships. Changing one variable forces the system to automatically recalculate and update all dependent geometry."
  },
  {
    q: "Concurrent Engineering is characterized by:",
    opts: [
      {t:"Parallel collaboration across departments", c:true}, 
      {t:"Early involvement of manufacturing engineers", c:true}, 
      {t:"Reduction of late-stage redesigns", c:true}, 
      {t:"Sequential 'throw-it-over-the-wall' workflows", c:false}
    ],
    exp: "<b>Concept: Management</b><br>Concurrent engineering breaks down silos. Teams collaborate simultaneously from day one, drastically reducing lead times and costly redesigns."
  },
  {
    q: "The GKS coordinate system 'SCR' represents:",
    opts: [
      {t:"System Coordinates Real", c:true}, 
      {t:"The mathematical continuous 3D world space", c:true}, 
      {t:"System Coordinates Normalized", c:false}, 
      {t:"Screen Device Resolution", c:false}
    ],
    exp: "<b>Concept: GKS Pipeline</b><br>SCR (System Coordinates Real) is the actual mathematical world-space coordinates before any normalization or scaling occurs."
  },
  {
    q: "Automated Guided Vehicles (AGVs) are used in a factory to:",
    opts: [
      {t:"Transport materials between machining cells", c:true}, 
      {t:"Deliver parts from the ASRS warehouse", c:true}, 
      {t:"Mill aluminum blocks", c:false}, 
      {t:"Generate CNC G-code", c:false}
    ],
    exp: "<b>Concept: Factory Hardware</b><br>AGVs are mobile robots dedicated exclusively to internal logistics and material transport. They do not perform machining."
  },
  {
    q: "Which of the following are examples of 'internal factors' affecting enterprise adaptability?",
    opts: [
      {t:"Management agility", c:true}, 
      {t:"Internal technology stack", c:true}, 
      {t:"Organizational structure", c:true}, 
      {t:"Global market demand", c:false}
    ],
    exp: "<b>Concept: Enterprise Management</b><br>Internal factors are things the company directly controls (Management, Technology, Organization). Market demand is an external factor."
  },
  {
    q: "An Expert System consists of which primary components?",
    opts: [
      {t:"Knowledge Base", c:true}, 
      {t:"Inference Engine", c:true}, 
      {t:"User Interface", c:true}, 
      {t:"Mechanical gripper", c:false}
    ],
    exp: "<b>Concept: AI Systems</b><br>Expert systems split the brain into a Knowledge Base (facts) and an Inference Engine (logic), accessed via a User Interface."
  },
  {
    q: "The ASRS (Automated Storage and Retrieval System) is responsible for:",
    opts: [
      {t:"Storing raw materials", c:true}, 
      {t:"Retrieving finished goods", c:true}, 
      {t:"Operating robotic warehouse cranes", c:true}, 
      {t:"Assembling PCBs", c:false}
    ],
    exp: "<b>Concept: Factory Hardware</b><br>ASRS is a massive robotic warehouse system that uses cranes to store and retrieve inventory automatically."
  },
  {
    q: "In GKS, the 'Workstation Active' state allows the system to:",
    opts: [
      {t:"Actively draw primitives on the screen", c:true}, 
      {t:"Receive graphical output", c:true}, 
      {t:"Initialize the operating system", c:false}, 
      {t:"Shut down completely", c:false}
    ],
    exp: "<b>Concept: GKS States</b><br>A workstation must be Active to actually render pixels. Just being 'Open' only means it is initialized in standby."
  },
  {
    q: "A Piping and Instrumentation Diagram (P&ID) utilizes:",
    opts: [
      {t:"Abstract logical symbols", c:true}, 
      {t:"Standardized ISA icons", c:true}, 
      {t:"Photorealistic 3D rendering", c:false}, 
      {t:"Exact physical scale lengths", c:false}
    ],
    exp: "<b>Concept: Industrial Schematics</b><br>A P&ID is a 2D logical map of fluid flow. It uses abstract symbols and completely ignores true physical dimensions or 3D scale."
  },
  {
    q: "Through-Hole Technology (THT) in electronics manufacturing requires:",
    opts: [
      {t:"Components with physical wire leads", c:true}, 
      {t:"Holes drilled completely through the PCB", c:true}, 
      {t:"Soldering on the opposite side of the board", c:true}, 
      {t:"Gluing components directly to the top surface", c:false}
    ],
    exp: "<b>Concept: Electronic Manufacturing</b><br>THT relies on physical wire pins inserted through drilled holes, unlike SMD which glues them directly to the surface."
  },
  {
    q: "Surface Mount Device (SMD) technology provides which advantages?",
    opts: [
      {t:"No drilling required", c:true}, 
      {t:"Higher component density", c:true}, 
      {t:"Mounting on both sides of the PCB", c:true}, 
      {t:"Easier manual soldering by hand", c:false}
    ],
    exp: "<b>Concept: Electronic Manufacturing</b><br>SMD eliminates drilling and allows massive miniaturization. However, the microscopic parts are much harder to solder by hand."
  },
  {
    q: "In PCB design, a 'Footprint' defines:",
    opts: [
      {t:"The 2D physical land pattern", c:true}, 
      {t:"The exact size of the copper solder pads", c:true}, 
      {t:"The logical schematic symbol", c:false}, 
      {t:"The software version", c:false}
    ],
    exp: "<b>Concept: PCB Design</b><br>The footprint is the exact, millimeter-perfect physical drawing of the copper pads that the real-world microchip will be soldered to."
  }
];
